require('dotenv').config();
const path=require('path'),express=require('express'),http=require('http'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),helmet=require('helmet'),compression=require('compression'),crypto=require('crypto');
const {Pool}=require('pg');
const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true,credentials:true}});
app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:'20kb'}));
const SECRET=process.env.JWT_SECRET||'development-only-change-me';
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const rowUser=r=>({_id:r.id,id:r.id,username:r.username,displayName:r.display_name,password:r.password,stats:{games:r.games,wins:r.wins,bluffs:r.bluffs,calls:r.calls}});
const safe=u=>({id:u.id||u._id,username:u.username,displayName:u.displayName,stats:u.stats});
const token=u=>jwt.sign({id:u.id||u._id,username:u.username,displayName:u.displayName},SECRET,{expiresIn:'30d'});
async function initDb(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY,username TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,password TEXT NOT NULL,games INT DEFAULT 0,wins INT DEFAULT 0,bluffs INT DEFAULT 0,calls INT DEFAULT 0,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS matches(id UUID PRIMARY KEY,room_code TEXT,winner UUID,players JSONB,turns INT,duration INT,created_at TIMESTAMPTZ DEFAULT NOW())`)}
const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);next()}catch{res.status(401).json({error:'Please sign in again.'})}};
app.post('/api/auth/register',async(req,res)=>{try{let {username,password,displayName}=req.body;username=(username||'').toLowerCase().trim();displayName=(displayName||username).trim();if(!/^[a-z0-9_]{3,18}$/.test(username)||!password||password.length<6)return res.status(400).json({error:'Use 3–18 letters, numbers or underscores, and a 6+ character password.'});const id=crypto.randomUUID(),hash=await bcrypt.hash(password,10);const {rows}=await pool.query('INSERT INTO users(id,username,display_name,password) VALUES($1,$2,$3,$4) RETURNING *',[id,username,displayName,hash]);const u=rowUser(rows[0]);res.json({token:token(u),user:safe(u)})}catch(e){res.status(409).json({error:e.code==='23505'?'That handle is taken.':'Could not create account.'})}});
app.post('/api/auth/login',async(req,res)=>{const {rows}=await pool.query('SELECT * FROM users WHERE username=$1',[(req.body.username||'').toLowerCase().trim()]);const u=rows[0]&&rowUser(rows[0]);if(!u||!await bcrypt.compare(req.body.password||'',u.password))return res.status(401).json({error:'Wrong handle or password.'});res.json({token:token(u),user:safe(u)})});
app.get('/api/me',auth,async(req,res)=>{const {rows}=await pool.query('SELECT * FROM users WHERE id=$1',[req.user.id]);if(!rows[0])return res.status(404).json({error:'Account not found.'});res.json({user:safe(rowUser(rows[0]))})});
app.get('/api/leaderboard',async(req,res)=>{const {rows}=await pool.query('SELECT * FROM users WHERE games>0 ORDER BY wins DESC,games ASC LIMIT 12');res.json(rows.map(rowUser).map(safe))});
const suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const rooms=new Map(); const code=()=>Math.random().toString(36).slice(2,6).toUpperCase();
function deck(){return suits.flatMap(s=>ranks.map(r=>({s,r,id:`${r}${s}`}))).sort(()=>Math.random()-.5)}
function view(g,uid){const me=g.players.find(p=>p.uid===uid);return {code:g.code,status:g.status,host:g.host,players:g.players.map(p=>({uid:p.uid,name:p.name,count:p.hand.length,connected:p.connected})),hand:me?.hand||[],turn:g.players[g.turn]?.uid,pileCount:g.pile.length,claim:g.claim,lastPlay:g.lastPlay?{name:g.lastPlay.name,count:g.lastPlay.count}:null,winner:g.winner,message:g.message,turns:g.turns}}
function emit(g){g.players.forEach(p=>{if(p.socket)io.to(p.socket).emit('state',view(g,p.uid))})}
function next(g){g.turn=(g.turn+1)%g.players.length;let n=0;while(!g.players[g.turn].connected&&n++<g.players.length)g.turn=(g.turn+1)%g.players.length}
function win(g,p){g.status='finished';g.winner=p.uid;g.message=`${p.name} emptied their hand.`;const dur=Math.round((Date.now()-g.started)/1000);pool.query('INSERT INTO matches(id,room_code,winner,players,turns,duration) VALUES($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),g.code,p.uid,JSON.stringify(g.players.map(x=>x.uid)),g.turns,dur]).catch(()=>{});g.players.forEach(x=>pool.query('UPDATE users SET games=games+1,wins=wins+$1 WHERE id=$2',[x.uid===p.uid?1:0,x.uid]).catch(()=>{}))}
io.use((s,n)=>{try{s.user=jwt.verify(s.handshake.auth.token,SECRET);n()}catch{n(new Error('unauthorized'))}});
io.on('connection',s=>{
 s.on('create',()=>{let c;do c=code();while(rooms.has(c));const g={code:c,host:s.user.id,status:'lobby',players:[{uid:s.user.id,name:s.user.displayName,hand:[],socket:s.id,connected:true}],pile:[],turn:0,claim:null,lastPlay:null,winner:null,message:'Invite someone with the room code.',turns:0};rooms.set(c,g);s.join(c);emit(g)});
 s.on('join',(raw,cb=()=>{})=>{const c=String(raw||'').toUpperCase().trim(),g=rooms.get(c);if(!g)return cb('Room not found.');let p=g.players.find(x=>x.uid===s.user.id);if(p){p.socket=s.id;p.connected=true;s.join(c);emit(g);return cb()}if(g.status!=='lobby')return cb('Game already started.');if(g.players.length>=6)return cb('Room is full.');g.players.push({uid:s.user.id,name:s.user.displayName,hand:[],socket:s.id,connected:true});s.join(c);g.message=`${s.user.displayName} joined.`;emit(g);cb()});
 s.on('start',(c,cb=()=>{})=>{const g=rooms.get(c);if(!g||g.host!==s.user.id)return cb('Only the host can start.');if(g.players.length<2)return cb('Invite at least one player.');const d=deck();g.players.forEach((p,i)=>p.hand=d.filter((_,j)=>j%g.players.length===i).sort((a,b)=>ranks.indexOf(a.r)-ranks.indexOf(b.r)));g.status='playing';g.started=Date.now();g.turn=0;g.pile=[];g.claim=null;g.lastPlay=null;g.message=`${g.players[0].name} leads.`;emit(g)});
 s.on('play',({code:c,cards,claim},cb=()=>{})=>{const g=rooms.get(c),p=g?.players[g.turn];if(!g||g.status!=='playing'||p?.uid!==s.user.id)return cb('Not your turn.');if(!Array.isArray(cards)||cards.length<1||cards.length>4)return cb('Choose 1–4 cards.');const chosen=[];for(const id of cards){const ix=p.hand.findIndex(x=>x.id===id);if(ix<0)return cb('Card unavailable.');chosen.push(...p.hand.splice(ix,1))}g.pile.push(...chosen);g.claim=claim;g.lastPlay={uid:p.uid,name:p.name,count:chosen.length,cards:chosen};g.turns++;g.message=`${p.name} claims ${chosen.length} × ${claim}.`;pool.query('UPDATE users SET bluffs=bluffs+$1 WHERE id=$2',[chosen.some(x=>x.r!==claim)?1:0,p.uid]).catch(()=>{});if(!p.hand.length){g.pendingWinner=p.uid}else{next(g)}emit(g);cb()});
 s.on('call',(c,cb=()=>{})=>{const g=rooms.get(c),caller=g?.players.find(x=>x.uid===s.user.id),lp=g?.lastPlay;if(!g||g.status!=='playing'||!lp||lp.uid===s.user.id)return cb('Nothing to call.');const liar=lp.cards.some(x=>x.r!==g.claim),played=g.players.find(x=>x.uid===lp.uid),loser=liar?played:caller;loser.hand.push(...g.pile);g.pile=[];g.message=liar?`${caller.name} caught ${played.name}. The pile is theirs.`:`${played.name} was honest. ${caller.name} takes the pile.`;pool.query('UPDATE users SET calls=calls+1 WHERE id=$1',[caller.uid]).catch(()=>{});g.lastPlay=null;g.pendingWinner=null;g.turn=g.players.findIndex(x=>x.uid===loser.uid);next(g);emit(g);cb()});
 s.on('pass-call',c=>{const g=rooms.get(c);if(!g||!g.pendingWinner)return;if(g.lastPlay?.uid===s.user.id)return;const p=g.players.find(x=>x.uid===g.pendingWinner);win(g,p);emit(g)});
 s.on('disconnect',()=>rooms.forEach(g=>{const p=g.players.find(x=>x.socket===s.id);if(p){p.connected=false;emit(g)}}));
});
const dist=path.join(__dirname,'client','dist');app.use(express.static(dist));app.get('*all',(req,res)=>res.sendFile(path.join(dist,'index.html')));
const PORT=process.env.PORT||3000;async function boot(){await initDb();server.listen(PORT,()=>console.log(`Bluff on ${PORT}`))}if(require.main===module)boot().catch(e=>{console.error(e);process.exit(1)});module.exports={app,server,boot};
