require('dotenv').config();
const path=require('path'),express=require('express'),http=require('http'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),helmet=require('helmet'),compression=require('compression');
const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true,credentials:true}});
app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:'20kb'}));
const SECRET=process.env.JWT_SECRET||'development-only-change-me';
const userSchema=new mongoose.Schema({username:{type:String,unique:true,lowercase:true,trim:true,minlength:3,maxlength:18},displayName:{type:String,trim:true,maxlength:24},password:String,stats:{games:{type:Number,default:0},wins:{type:Number,default:0},bluffs:{type:Number,default:0},calls:{type:Number,default:0}}},{timestamps:true});
const User=mongoose.model('User',userSchema);
const matchSchema=new mongoose.Schema({roomCode:String,winner:String,players:[String],turns:Number,duration:Number},{timestamps:true});const Match=mongoose.model('Match',matchSchema);
const token=u=>jwt.sign({id:u._id,username:u.username,displayName:u.displayName},SECRET,{expiresIn:'30d'});
const safe=u=>({id:u._id,username:u.username,displayName:u.displayName,stats:u.stats});
const auth=async(req,res,next)=>{try{const t=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(t,SECRET);next()}catch{res.status(401).json({error:'Please sign in again.'})}};
app.post('/api/auth/register',async(req,res)=>{try{let {username,password,displayName}=req.body;username=(username||'').toLowerCase().trim();displayName=(displayName||username).trim();if(!/^[a-z0-9_]{3,18}$/.test(username)||!password||password.length<6)return res.status(400).json({error:'Use 3–18 letters, numbers or underscores, and a 6+ character password.'});const u=await User.create({username,displayName,password:await bcrypt.hash(password,10)});res.json({token:token(u),user:safe(u)})}catch(e){res.status(409).json({error:e.code===11000?'That handle is taken.':'Could not create account.'})}});
app.post('/api/auth/login',async(req,res)=>{const u=await User.findOne({username:(req.body.username||'').toLowerCase().trim()});if(!u||!await bcrypt.compare(req.body.password||'',u.password))return res.status(401).json({error:'Wrong handle or password.'});res.json({token:token(u),user:safe(u)})});
app.get('/api/me',auth,async(req,res)=>{const u=await User.findById(req.user.id);res.json({user:safe(u)})});
app.get('/api/leaderboard',async(req,res)=>{const users=await User.find({'stats.games':{$gt:0}}).sort({'stats.wins':-1,'stats.games':1}).limit(12);res.json(users.map(safe))});
const suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const rooms=new Map(); const code=()=>Math.random().toString(36).slice(2,6).toUpperCase();
function deck(){return suits.flatMap(s=>ranks.map(r=>({s,r,id:`${r}${s}`}))).sort(()=>Math.random()-.5)}
function view(g,uid){const me=g.players.find(p=>p.uid===uid);return {code:g.code,status:g.status,host:g.host,players:g.players.map(p=>({uid:p.uid,name:p.name,count:p.hand.length,connected:p.connected})),hand:me?.hand||[],turn:g.players[g.turn]?.uid,pileCount:g.pile.length,claim:g.claim,lastPlay:g.lastPlay?{name:g.lastPlay.name,count:g.lastPlay.count}:null,winner:g.winner,message:g.message,turns:g.turns}}
function emit(g){g.players.forEach(p=>{if(p.socket)io.to(p.socket).emit('state',view(g,p.uid))})}
function next(g){g.turn=(g.turn+1)%g.players.length;let n=0;while(!g.players[g.turn].connected&&n++<g.players.length)g.turn=(g.turn+1)%g.players.length}
function win(g,p){g.status='finished';g.winner=p.uid;g.message=`${p.name} emptied their hand.`;const dur=Math.round((Date.now()-g.started)/1000);Match.create({roomCode:g.code,winner:p.uid,players:g.players.map(x=>x.uid),turns:g.turns,duration:dur}).catch(()=>{});g.players.forEach(x=>User.findByIdAndUpdate(x.uid,{$inc:{'stats.games':1,...(x.uid===p.uid?{'stats.wins':1}:{})}}).catch(()=>{}))}
io.use((s,n)=>{try{s.user=jwt.verify(s.handshake.auth.token,SECRET);n()}catch{n(new Error('unauthorized'))}});
io.on('connection',s=>{
 s.on('create',()=>{let c;do c=code();while(rooms.has(c));const g={code:c,host:s.user.id,status:'lobby',players:[{uid:s.user.id,name:s.user.displayName,hand:[],socket:s.id,connected:true}],pile:[],turn:0,claim:null,lastPlay:null,winner:null,message:'Invite someone with the room code.',turns:0};rooms.set(c,g);s.join(c);emit(g)});
 s.on('join',(raw,cb=()=>{})=>{const c=String(raw||'').toUpperCase().trim(),g=rooms.get(c);if(!g)return cb('Room not found.');let p=g.players.find(x=>x.uid===s.user.id);if(p){p.socket=s.id;p.connected=true;s.join(c);emit(g);return cb()}if(g.status!=='lobby')return cb('Game already started.');if(g.players.length>=6)return cb('Room is full.');g.players.push({uid:s.user.id,name:s.user.displayName,hand:[],socket:s.id,connected:true});s.join(c);g.message=`${s.user.displayName} joined.`;emit(g);cb()});
 s.on('start',(c,cb=()=>{})=>{const g=rooms.get(c);if(!g||g.host!==s.user.id)return cb('Only the host can start.');if(g.players.length<2)return cb('Invite at least one player.');const d=deck();g.players.forEach((p,i)=>p.hand=d.filter((_,j)=>j%g.players.length===i).sort((a,b)=>ranks.indexOf(a.r)-ranks.indexOf(b.r)));g.status='playing';g.started=Date.now();g.turn=0;g.pile=[];g.claim=null;g.lastPlay=null;g.message=`${g.players[0].name} leads.`;emit(g)});
 s.on('play',({code:c,cards,claim},cb=()=>{})=>{const g=rooms.get(c),p=g?.players[g.turn];if(!g||g.status!=='playing'||p?.uid!==s.user.id)return cb('Not your turn.');if(!Array.isArray(cards)||cards.length<1||cards.length>4)return cb('Choose 1–4 cards.');const chosen=[];for(const id of cards){const ix=p.hand.findIndex(x=>x.id===id);if(ix<0)return cb('Card unavailable.');chosen.push(...p.hand.splice(ix,1))}g.pile.push(...chosen);g.claim=claim;g.lastPlay={uid:p.uid,name:p.name,count:chosen.length,cards:chosen};g.turns++;g.message=`${p.name} claims ${chosen.length} × ${claim}.`;User.findByIdAndUpdate(p.uid,{$inc:{'stats.bluffs':chosen.some(x=>x.r!==claim)?1:0}}).catch(()=>{});if(!p.hand.length){g.pendingWinner=p.uid}else{next(g)}emit(g);cb()});
 s.on('call',(c,cb=()=>{})=>{const g=rooms.get(c),caller=g?.players.find(x=>x.uid===s.user.id),lp=g?.lastPlay;if(!g||g.status!=='playing'||!lp||lp.uid===s.user.id)return cb('Nothing to call.');const liar=lp.cards.some(x=>x.r!==g.claim),played=g.players.find(x=>x.uid===lp.uid),loser=liar?played:caller;loser.hand.push(...g.pile);g.pile=[];g.message=liar?`${caller.name} caught ${played.name}. The pile is theirs.`:`${played.name} was honest. ${caller.name} takes the pile.`;User.findByIdAndUpdate(caller.uid,{$inc:{'stats.calls':1}}).catch(()=>{});g.lastPlay=null;g.pendingWinner=null;g.turn=g.players.findIndex(x=>x.uid===loser.uid);next(g);emit(g);cb()});
 s.on('pass-call',c=>{const g=rooms.get(c);if(!g||!g.pendingWinner)return;if(g.lastPlay?.uid===s.user.id)return;const p=g.players.find(x=>x.uid===g.pendingWinner);win(g,p);emit(g)});
 s.on('disconnect',()=>rooms.forEach(g=>{const p=g.players.find(x=>x.socket===s.id);if(p){p.connected=false;emit(g)}}));
});
const dist=path.join(__dirname,'client','dist');app.use(express.static(dist));app.get('*all',(req,res)=>res.sendFile(path.join(dist,'index.html')));
const PORT=process.env.PORT||3000;async function boot(){await mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/bluff');server.listen(PORT,()=>console.log(`Bluff on ${PORT}`))}if(require.main===module)boot().catch(e=>{console.error(e);process.exit(1)});module.exports={app,server,boot};
